-- 1  NOT NULL   --> Evita que se ingresen valores nulos a una columa especifica
-- 2  UNIQUE     --> Evita que se ingresen valores duplicados en una columna o conjunto de columnas
-- 3  UNSIGNED   --> Evita que se ingresen numeros negativos a una columna especifica
-- 4  